# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
