# Generated by Django 4.2 on 2023-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
